### ISSUE TITLE
Different Directories

### ISSUE THREAD

**Issue by kmanthei** [kmanthei/kmanthei.github.io#1]
We are trying to figure out how to run the python file on different computers despite having different directories and name for the necessary file. The person who wrote the code imports from their downloads and directory, but the rest of the team cannot open and successfully run the same code without a traceback error on line 5 since we do not share the same directory and download name. We need to figure out how to allow access to all or another solution.

**Comment by nyanford** [comment]
I believe making the code a for loop might help assist with that issue. 

The professor sent some links that could potentially help fix that problem as well.

**Comment by kmanthei** [comment]
Changing the directory to your current directory and whatever you have the log file named on the designated computer solves this issue. I successfully was able to run the code on my computer after changing to my download directory and the name which I had the file data under.
