### ISSUE TITLE
Professor's Advice

### ISSUE THREAD

**Issue by edengracee** [kmanthei/kmanthei.github.io#3]
The professor suggests trying this: 
Use the urllib module to download a file from the Internet:
https://gist.github.com/amikeal/4e2847e3977a787e071e81014fe43390
Use the Python open() function to read a file on disk:
https://gist.github.com/amikeal/8b4182edbabc4197fa2e44e2894ee059

**Comment by kmanthei** [comment]
We were able to open the file on our own computers by changing it to the file name saved on our computers. It successfully worked.
